parameters:
#    fabien_player_manager.example.class: Fabien\PlayerManagerBundle\Example

services:
#    fabien_player_manager.example:
#        class: %fabien_player_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
